version: '2'

services:
  alpine-nginx-with-theia-web-ide-hobo: 
    build: .
    image: hackinglab/alpine-nginx-with-theia-web-ide:3.2
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass
    ports:
      - "8000:80"
