
services:
  alpine-nginx-with-theia-web-ide: 
    build: .
    image: hackinglab/alpine-nginx-with-theia-web-ide-hl:3.2
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass
    ports:
      - "8000:80"
